"""Command-line interface for Sim-city."""

from __future__ import annotations

import logging

import typer
import uvicorn

app = typer.Typer(help="Sim-city — synthetic city simulator.")


@app.command()
def serve(
    host: str = "127.0.0.1",
    port: int = 8000,
    n_agents: int = 10000,
    grid_size: int = 150,
    seed: int = 42,
    log_level: str = "info",
) -> None:
    """Run the simulator HTTP/WebSocket server.

    First boot generates personas into ~/.citysim/citysim.db (10k rows,
    a few seconds). Subsequent boots reuse the stored personas if the
    world signature (n_agents/seed/grid_size) matches.
    """
    logging.basicConfig(level=log_level.upper())
    from citysim.server.app import create_app

    application = create_app(n_agents=n_agents, grid_size=grid_size, seed=seed)
    uvicorn.run(application, host=host, port=port, log_level=log_level)


@app.command()
def info() -> None:
    """Print the build version + storage status."""
    from citysim import __version__
    from citysim.store import PersonaStore, default_db_path

    typer.echo(f"citysim {__version__}")
    db = default_db_path()
    if db.exists():
        store = PersonaStore(db)
        typer.echo(f"DB: {db}")
        typer.echo(f"Personas stored: {store.count():,}")
        sig = store.get_meta("world_signature")
        if sig:
            typer.echo(f"World signature: {sig}")
    else:
        typer.echo(f"DB: {db} (not yet created — run `citysim serve` once)")


@app.command(name="regen-personas")
def regen_personas(
    n_agents: int = 10000,
    grid_size: int = 150,
    seed: int = 42,
) -> None:
    """Wipe ~/.citysim/citysim.db and regenerate personas from scratch."""
    from citysim.store import PersonaStore
    from citysim.world.establishments import place_establishments
    from citysim.world.grid import generate_grid
    from citysim.world.personas import load_or_generate_personas

    store = PersonaStore()
    grid = generate_grid(size=grid_size, seed=seed)
    establishments = place_establishments(grid, seed=seed)
    personas = load_or_generate_personas(
        grid,
        establishments,
        n=n_agents,
        seed=seed,
        store=store,
        force_regenerate=True,
    )
    typer.echo(f"Generated {len(personas):,} personas → {store.path}")


@app.command(name="show-persona")
def show_persona(agent_id: str) -> None:
    """Print one persona's full record (handy for sanity-checking dialogue)."""
    from citysim.store import PersonaStore

    store = PersonaStore()
    row = store.get(agent_id)
    if not row:
        typer.echo(f"No persona with id {agent_id!r}")
        raise typer.Exit(1)
    typer.echo(f"--- {row.agent_id} ---")
    typer.echo(f"  age={row.age} gender={row.gender} edu={row.education}")
    typer.echo(f"  occupation={row.occupation} income={row.income_band}")
    typer.echo(f"  household={row.household_id} role={row.household_role}")
    typer.echo(f"  home=({row.home_x},{row.home_y}) work=({row.work_x},{row.work_y})")
    typer.echo(f"  prefs={row.prefs}")
    typer.echo(f"  needs={row.needs}")
    typer.echo("")
    typer.echo(f"  card: {row.card_text}")


@app.command(name="run-dialogue")
def run_dialogue_cmd(
    buyer_id: str | None = None,
    store_id: str | None = None,
    n_agents: int = 10000,
    grid_size: int = 150,
    seed: int = 42,
    max_turns: int = 6,
    no_extract: bool = False,
) -> None:
    """Run one buyer-seller dialogue end-to-end and print the transcript.

    Picks a random adult buyer and a random shoppable establishment if not
    specified. Streams turns to stdout as they're generated by the local
    LLM, then runs structured-outcome extraction (audit tier, falls back
    to rule-based if no OpenAI key).

    Examples:
      citysim run-dialogue
      citysim run-dialogue --buyer-id a000042
      citysim run-dialogue --store-id e0007 --max-turns 8
    """
    import random as _random

    from citysim.interaction import (
        DialogueTurn,
        find_employee,
        pick_random_buyer,
        pick_random_store,
        run_dialogue,
    )
    from citysim.server.sim import build_sim
    from citysim.store import EventLog

    typer.echo("Loading world...")
    sim = build_sim(n_agents=n_agents, grid_size=grid_size, seed=seed)

    rng = _random.Random()

    if buyer_id:
        buyer = sim.persona_by_id.get(buyer_id)
        if buyer is None:
            typer.echo(f"No persona with id {buyer_id!r}")
            raise typer.Exit(1)
    else:
        buyer = pick_random_buyer(sim.personas, rng)

    if store_id:
        store = next((e for e in sim.establishments if e.id == store_id), None)
        if store is None:
            typer.echo(f"No establishment with id {store_id!r}")
            raise typer.Exit(1)
        seller = find_employee(store, sim.personas)
        if seller is None:
            typer.echo(f"Establishment {store_id!r} has no employees in this world")
            raise typer.Exit(1)
    else:
        picked = pick_random_store(sim.establishments, sim.personas, rng)
        if picked is None:
            typer.echo("No shoppable establishment with employees found.")
            raise typer.Exit(1)
        store, seller = picked

    typer.echo("")
    typer.echo(
        f"Buyer:  {buyer.agent_id} — {buyer.age} {buyer.gender} {buyer.occupation} ({buyer.income_band})"
    )
    typer.echo(f"        {buyer.card_text}")
    typer.echo(f"Seller: {seller.agent_id} — {seller.occupation} at {store.kind.value}")
    typer.echo(f"        {seller.card_text}")
    typer.echo("")
    typer.echo(f"Running dialogue (≤{max_turns} turns) on local Llama...")
    typer.echo("")

    def _print_turn(turn: DialogueTurn) -> None:
        typer.echo(f"  {turn.speaker.upper()}: {turn.text}")

    log = EventLog()
    result = run_dialogue(
        buyer,
        seller,
        store,
        max_turns=max_turns,
        extract_outcome=not no_extract,
        log_to=log,
        on_turn=_print_turn,
    )

    typer.echo("")
    typer.echo(f"Ended: {result.end_reason} after {result.duration_s:.1f}s")
    typer.echo(f"Outcome: {result.outcome}")
    typer.echo(f"Logged to {log.dir}")


@app.command(name="llm-test")
def llm_test(
    prompt: str = "Say hello in five words.",
    provider: str | None = None,
    model: str | None = None,
    tier: str = "agent",
) -> None:
    """Smoke-test the LLM gateway end-to-end.

    Default tier is ``agent`` — routed to the local Ollama model. Pass
    ``--tier audit`` to hit OpenAI, or ``--provider openai`` to override
    explicitly.
    """
    from citysim.llm import LLMMessage, get_gateway

    gateway = get_gateway(tier=tier, provider_override=provider, model_override=model)
    typer.echo(f"Tier: {tier}  Provider: {gateway.provider}  Model: {gateway.model}")
    resp = gateway.chat([LLMMessage(role="user", content=prompt)], max_tokens=64)
    typer.echo(f"Reply: {resp.text.strip()}")
    if resp.usage:
        typer.echo(f"Tokens: {resp.usage}")


if __name__ == "__main__":
    app()
